### ISSUE TITLE
variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by NoahDragon** [10sr/editorconfig-custom-majormode-el#5]
Posted on https://github.com/editorconfig/editorconfig-emacs/issues/147

Based on the error message seems it is from editorconfig-emacs, but if anyone knows the solution, that would be really appreciated.

**Comment by NoahDragon** [comment]
I have set a file to use emacs mode XML. I found on the *Messages* showing `Using vacuous schema [95 times]`, but if remove the package, it only shows `Using vacuous schema`. Seems like it has been repeatedly applying the schema check.

**Comment by 10sr** [comment]
Thanks for bug report!

It seems it is because xml-mode is an alias for nxml-mode and this library does not know that.
This should be fixed, but as a quick fix you can set the value to nxml instead of xml to avoid this error.

**Comment by 10sr** [comment]
I believe this should be fixed now. Try the new version :pray:
