### ISSUE TITLE
Typo in URL metadata (as read by package-buffer-info)

### ISSUE THREAD

**Issue by dmringo** [10sr/editorconfig-custom-majormode-el#7]
[The URL given in the package description](https://github.com/10sr/editorconfig-custom-majormode-el/blob/ae613f0a56364afbbab19d4377c108406d5cfc7c/editorconfig-custom-majormode.el#L4) contains a spurious hyphen.  It should be `https://github.com/10sr/editorconfig-custom-majormode-el`.

**Comment by 10sr** [comment]
Thanks!
